#ifndef __KVSIMREADER_ELIE2023_ASYM_H
#define __KVSIMREADER_ELIE2023_ASYM_H

#include "KVSimReader_ELIE2023.h"

/**
 \class KVSimReader_ELIE2023_asym
 \brief Read ASCII files generated by ELIE (new format 2022)

 Write a detailed documentation for your class here, see doxygen manual for help.

 \author John Frankland
 \date Fri Nov  4 17:07:18 2022
*/

class KVSimReader_ELIE2023_asym : public KVSimReader_ELIE2023 {
protected:
   void define_output_filename();
public:
   KVSimReader_ELIE2023_asym() : KVSimReader_ELIE2023() {}
   KVSimReader_ELIE2023_asym(KVString filename) : KVSimReader_ELIE2023()
   {
      ConvertEventsInFile(filename);
   }

   ClassDef(KVSimReader_ELIE2023_asym, 1) //Read ASCII files generated by ELIE (new format 2022)
};

#endif
