#ifndef __KVSIMREADER_ELIE2023_H
#define __KVSIMREADER_ELIE2023_H

#include "KVSimReader_ELIE.h"

/**
 \class KVSimReader_ELIE2023
 \brief Read ASCII files generated by ELIE (new format 2022)

 This class is for reading primary events before secondary decay,
 i.e. output files with names like: elie_58_197_32_1000_primary.output

The events will be stored in a ROOT file with a name like:
~~~~
ELIE_[PROJ]_[TARG]_[EBEAM]AMeV_PRIM.root
~~~~
 This file will contain a TTree called "ELIE" with a branch "Simulated_evts"

 \author John Frankland
 \date Fri Nov  4 12:12:22 2022
*/

class KVSimReader_ELIE2023 : public KVSimReader_ELIE {
public:
   KVSimReader_ELIE2023() : KVSimReader_ELIE() {}
   KVSimReader_ELIE2023(KVString filename) : KVSimReader_ELIE()
   {
      ConvertEventsInFile(filename);
   }

   Bool_t ReadHeader();
   Bool_t ReadEvent();
   Bool_t ReadNucleus();

   ClassDef(KVSimReader_ELIE2023, 1) //Read ASCII files generated by ELIE (new format 2022)
};

#endif
